import React from "react";
import {createRoot} from "react-dom/client";
import "./styles.css";
const tg=(window as any).Telegram?.WebApp; const API=import.meta.env.VITE_API_URL||"http://localhost:3000";
async function api(path:string,options:RequestInit={}){const h=new Headers(options.headers);h.set("Content-Type","application/json");if(tg?.initData)h.set("x-telegram-init-data",tg.initData);const r=await fetch(API+"/api"+path,{...options,headers:h});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||"Server xatosi");return r.json()}
function money(v:any){return new Intl.NumberFormat("uz-UZ").format(Number(v||0))}
function App(){const[tab,setTab]=React.useState("dashboard"),[me,setMe]=React.useState<any>(null),[a,setA]=React.useState<any>(null),[customers,setCustomers]=React.useState<any[]>([]),[services,setServices]=React.useState<any[]>([]),[parts,setParts]=React.useState<any[]>([]),[orders,setOrders]=React.useState<any[]>([]),[debts,setDebts]=React.useState<any[]>([]),[err,setErr]=React.useState("");
const load=()=>Promise.all([api("/me"),api("/analytics"),api("/customers"),api("/services"),api("/parts"),api("/orders"),api("/debts")]).then(([m,x,c,s,p,o,d])=>{setMe(m);setA(x);setCustomers(c);setServices(s);setParts(p);setOrders(o);setDebts(d)});
React.useEffect(()=>{tg?.ready?.();tg?.expand?.();api("/auth/telegram",{method:"POST"}).then(load).catch(e=>setErr(e.message))},[]);
if(err)return <main><h1>AVTO SERVICE NASIYA</h1><div className="error">{err}</div><p>Telegram Mini App ichidan oching.</p></main>;
return <div className="app"><header><div><small>AVTO SERVICE NASIYA</small><h1>{me?.workshop?.name||"Avto Service"}</h1></div><span className="avatar">{(me?.user?.name||"A")[0]}</span></header>
<main>
{tab==="dashboard"&&<><section className="hero"><span>XASANBOY AUTO SERVICE</span><strong>Boshqaruv paneli</strong><p>Servis, mijoz va qarzdorliklar bir joyda.</p></section><section className="grid"><Card n={a?.orders??0} t="Buyurtmalar"/><Card n={money(a?.revenue)+" so‘m"} t="Aylanma"/><Card n={money(a?.paid)+" so‘m"} t="To‘langan"/><Card n={money(a?.debt)+" so‘m"} t="Qarz"/></section><button className="primary" onClick={()=>setTab("service")}>＋ YANGI SERVIS</button><List title="Oxirgi buyurtmalar" items={orders.slice(0,5)} amountKey="total"/></>}
{tab==="customers"&&<Customers customers={customers} onDone={load}/>} {tab==="payments"&&<Payments orders={orders.filter(x=>Number(x.debt)>0)} onDone={load}/>} 
{tab==="service"&&<ServiceForm customers={customers} services={services} parts={parts} onDone={()=>load()}/>}
{tab==="debts"&&<><SectionTitle title="Qarzdorlar" count={debts.length}/><List title="" items={debts} amountKey="debt" debt/></>}
{tab==="analytics"&&<><SectionTitle title="Analitika" count={a?.orders||0}/><section className="panel"><h3>Moliyaviy ko‘rsatkichlar</h3><p>Aylanma: <b>{money(a?.revenue)} so‘m</b></p><p>To‘langan: <b>{money(a?.paid)} so‘m</b></p><p>Qarz: <b>{money(a?.debt)} so‘m</b></p></section></>}
{tab==="settings"&&<section className="panel"><h2>Sozlamalar</h2><p>Ustaxona: {me?.workshop?.name}</p><p>Foydalanuvchi: {me?.user?.name}</p></section>}
</main><nav>{[["⌂","Dashboard","dashboard"],["👥","Mijozlar","customers"],["🔧","Servis","service"],["💳","To‘lov","payments"],["⚙","Sozlamalar","settings"]].map(x=><button className={tab===x[2]?"active":""} onClick={()=>setTab(x[2])} key={x[2]}><span>{x[0]}</span>{x[1]}</button>)}</nav></div>}
function Card(p:{n:any;t:string}){return <div className="card"><strong>{p.n}</strong><span>{p.t}</span></div>}
function SectionTitle(p:{title:string;count:any}){return <div className="sectionHead"><h2>{p.title}</h2><b>{p.count}</b></div>}
function List(p:{title:string;items:any[];amountKey?:string;customer?:boolean;debt?:boolean}){return <section>{p.title&&<div className="sectionHead"><h2>{p.title}</h2></div>}<div className="list">{p.items.map(x=><div className="row" key={x.id}><div><b>{p.customer?x.name:x.customer?.name||"Mijoz"}</b><small>{p.customer?(x.vehicles?.map((v:any)=>v.plate).join(" · ")||x.phone||""):x.vehicle?.plate||"—"}</small></div>{p.customer?null:<strong>{money(x[p.amountKey||"total"])} so‘m</strong>}</div>)}{!p.items.length&&<div className="empty">Ma’lumot yo‘q</div>}</div></section>}
function Customers(p:{customers:any[];onDone:()=>void}){const[name,setName]=React.useState(""),[phone,setPhone]=React.useState(""),[busy,setBusy]=React.useState(false),[msg,setMsg]=React.useState("");const add=async()=>{if(!name.trim())return setMsg("Ism kiriting");setBusy(true);try{await api("/customers",{method:"POST",body:JSON.stringify({name,phone})});setName("");setPhone("");setMsg("✅ Mijoz qo‘shildi");p.onDone()}catch(e:any){setMsg("❌ "+e.message)}finally{setBusy(false)}};return <section><SectionTitle title="Mijozlar" count={p.customers.length}/><input placeholder="Ism familiya" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="+998..." value={phone} onChange={e=>setPhone(e.target.value)}/><button className="primary" disabled={busy} onClick={add}>{busy?"Saqlanmoqda...":"＋ MIJOZ QO‘SHISH"}</button><List title="" items={p.customers} customer/></section>}
function Payments(p:{orders:any[];onDone:()=>void}){const[o,setO]=React.useState(""),[amount,setAmount]=React.useState(""),[msg,setMsg]=React.useState("");const pay=async()=>{if(!o||Number(amount)<=0)return setMsg("Buyurtma va summa kiriting");try{await api("/payments",{method:"POST",body:JSON.stringify({orderId:o,amount:Number(amount)})});setMsg("✅ To‘lov saqlandi");setAmount("");p.onDone()}catch(e:any){setMsg("❌ "+e.message)}};return <section><SectionTitle title="To‘lov kiritish" count={p.orders.length}/><select value={o} onChange={e=>setO(e.target.value)}><option value="">Qarzli buyurtmani tanlang</option>{p.orders.map(x=><option key={x.id} value={x.id}>{x.customer?.name} · {x.vehicle?.plate} · {money(x.debt)} so‘m</option>)}</select><input type="number" placeholder="To‘lov summasi" value={amount} onChange={e=>setAmount(e.target.value)}/><button className="primary" onClick={pay}>TO‘LOVNI SAQLASH</button>{msg&&<p>{msg}</p>}</section>}
function ServiceForm(p:{customers:any[];services:any[];parts:any[];onDone:()=>void}){const[c,setC]=React.useState(""),[v,setV]=React.useState(""),[name,setName]=React.useState(""),[price,setPrice]=React.useState(""),[items,setItems]=React.useState<any[]>([]),[paid,setPaid]=React.useState(""),[due,setDue]=React.useState(""),[busy,setBusy]=React.useState(false),[msg,setMsg]=React.useState("");
const customer=p.customers.find(x=>x.id===c);const add=()=>{if(!name||!price)return;setItems([...items,{name,unitPrice:Number(price),quantity:1}]);setName("");setPrice("")};
const submit=async()=>{if(!c||!v||!items.length)return setMsg("Mijoz, avtomobil va kamida bitta ish kiriting");setBusy(true);try{await api("/orders",{method:"POST",body:JSON.stringify({customerId:c,vehicleId:v,items,paid:Number(paid||0),dueDate:due||null})});setMsg("✅ Servis yaratildi");p.onDone();}catch(e:any){setMsg("❌ "+e.message)}finally{setBusy(false)}};
return <section><SectionTitle title="Yangi servis" count={items.length}/><select value={c} onChange={e=>{setC(e.target.value);setV("")}}><option value="">Mijozni tanlang</option>{p.customers.map(x=><option key={x.id} value={x.id}>{x.name} — {x.phone||""}</option>)}</select>{customer&&<select value={v} onChange={e=>setV(e.target.value)}><option value="">Avtomobilni tanlang</option>{customer.vehicles.map((x:any)=><option key={x.id} value={x.id}>{x.make} {x.model||""} — {x.plate}</option>)}</select>}<div className="addline"><input placeholder="Ish / detal nomi" value={name} onChange={e=>setName(e.target.value)}/><input type="number" placeholder="Narx" value={price} onChange={e=>setPrice(e.target.value)}/><button onClick={add}>＋</button></div>{items.map((x,i)=><div className="row" key={i}><span>{x.name}</span><b>{money(x.unitPrice)} so‘m</b></div>)}<input type="number" placeholder="Boshlang‘ich to‘lov" value={paid} onChange={e=>setPaid(e.target.value)}/><input type="date" value={due} onChange={e=>setDue(e.target.value)}/><button className="primary" disabled={busy} onClick={submit}>{busy?"Saqlanmoqda...":"SERVISNI SAQLASH"}</button>{msg&&<p>{msg}</p>}</section>}
createRoot(document.getElementById("root")!).render(<App/>);